nostr:
  privateKey: 0e79e5e90754cb23275477a32bd1c42bee28dc78a0b10693dfd8cac6852363fd
  relayUrls:
    - ws://localhost:10547
mcp:
  name: DVM MCP Bridge
  about: MCP-enabled DVM providing AI and computational tools
  clientName: DVM MCP Bridge Client
  clientVersion: 1.0.0
  servers:
    - name: hello
      command: bun
      args:
        - --cwd
        - /home/user/Documents/dev/gz/js-ts/bun/mcp-echo
        - start:mcp
whitelist:
  allowedPubkeys: []
